### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by asg017** [datasette-io/datasette-litestream#1]
- [x] Some form of a "status" page at `/-/litestream-status`
  - [x] Look at logs from litestream process (store in-memory)
  - [x] Prometheus metrics, if enabled?
- [x]  Distribute pre-compiled wheels of litestream binaries
- [x] Upstream contribute to litestream to include MacOS ARM builds?
